### ISSUE TITLE
Add HalfCB to control blocks

### ISSUE THREAD

**Issue by danyill** [danyill/oscd-tp-multicast-naming#32]
https://github.com/transpower-nz/open-scd/issues/2

**Comment by danyill** [comment]
@Uffel3 usually we choose a control block name which is a verb and aligns with what we've previously chosen.

`HalfCB` doesn't obviously do either.

Why wouldn't you just call it `TripCBFail`?

**Comment by Uffel3** [comment]
Good point. I was probably worried that someone could mistake it with the `TripCBFail` of the BZ protection. I shall take a note for the SEL-411L-2. 

However, this GCB contains Trip(CBFail) and ARecl block signals. Shall we separate those into individual GCB's or stick with a combined GCB? If so, should we choose a better name for the GCB?

**Comment by Uffel3** [comment]
After mulling this over many times, I came to the conclusion that I refuse to create another GOOSE control block for just one data attribute. 

It cannot be named `TripCBFail` due to previous reasons (and it would be difficult to understand). Here are some ideas for names

* Ctl_HalfCB
* Ctl - HalfCB
* HalfCB
* HalfCB_Ctl

I agree that the name should tell us the function, but I struggle with this name. So for the moment, I will stick with `HalfCB_Ctl`, because we use the name `AdjBusCouplerInd` already which is of similar style.

We also have to come up with a GCB name for the **SEL-2440** bay controller that is connected to the half CB disconnectors and single bus CB bus section disconnectors (I need it for the VT selection checks). We could do the following.

* Bus section disconnectors: We stick with `AdjBusCouplerInd`
* Half CB disconnectors: `HalfCB_Ind`

**Comment by danyill** [comment]
We'll use `HalfCB_Ctl`
